# Generated by Django 2.2.19 on 2022-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220311_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
